name: First_workflow
on: workflow_dispatch
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: first step
              run: echo "This is"
            - name: print good bye
              run: | 
                   echo "This is one first workflow"
                   echo "Good bye"
