name: Second_workflow
on:
    push:
        branches: 
            - main
jobs:
    second_job:
        runs-on: ubuntu-latest
        steps:
            - name: first step
              run: echo "This is second workflow"
            - name: print good bye
              run: | 
                   echo "This is 2nd workflow"
                   echo "Good bye"
